# Generated by Django 5.2.8 on 2025-11-13 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'Can View'), ('can_create', 'Can Create'), ('can_delete', 'Can Delete'), ('can_edit', 'Can Edit')]},
        ),
    ]
