[project]
name = "social-media-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "coverage>=7.13.0",
    "django>=6.0",
    "djangorestframework>=3.16.1",
    "djangorestframework-stubs>=3.16.6",
    "pillow>=12.0.0",
]

[dependency-groups]
dev = [
    "black>=25.12.0",
    "django-silk>=5.4.3",
    "drf-spectacular>=0.29.0",
]
