# Generated by Django 6.0 on 2025-12-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_picture/default.jpg",
                null=True,
                upload_to="profile_picture",
            ),
        ),
    ]
